"""Shared, sensor-only perception for the two no-training LIBERO routes."""

from .adapters import (
    RouteBScenePerceptionAdapter,
    RouteCSceneEstimatorAdapter,
    coerce_rgbd_frame,
    make_default_perception,
)
from .gallery import (
    DEFAULT_ASSET_ROOT,
    GALLERY_QUERY_PRIORS,
    LIBERO_OBJECT_LABELS,
    OBJECT_GALLERY_SPECS,
    PUBLIC_ASSET_GALLERY_SPECS,
    AssetPrototype,
    Classification,
    GalleryQueryPrior,
    PublicAssetGallerySpec,
    TextureSizeGallery,
    collision_aabb_dimensions,
    hsv_histogram,
)
from .fusion import fuse_instances_3d, resolve_geometric_selector
from .geometry import (
    ComponentConfig,
    GeometryError,
    backproject_frame,
    center_ray_intersection,
    connected_components_3d,
    estimate_horizontal_support,
    fit_observed_geometry,
    fuse_rgbd_frames,
)
from .grounding_dino import (
    DEFAULT_GROUNDING_DINO_TINY,
    BoxGeometryExtractor,
    FrozenBoxDetector,
    GroundingDINOBoxDetector,
)
from .pipeline import PerceptionConfig, PerceptionDiagnostics, SensorOnlyScenePerception
from .schema import (
    BoxDetection,
    InstanceSelector,
    ObjectInstance,
    ObservedGeometry,
    PointCloud,
    RGBDFrame,
    SceneObservation,
    SelectorKind,
    normalize_label,
    scene_camera_capture_ids,
    scene_capture_id,
)

__all__ = [
    "DEFAULT_ASSET_ROOT",
    "DEFAULT_GROUNDING_DINO_TINY",
    "GALLERY_QUERY_PRIORS",
    "LIBERO_OBJECT_LABELS",
    "OBJECT_GALLERY_SPECS",
    "PUBLIC_ASSET_GALLERY_SPECS",
    "AssetPrototype",
    "BoxDetection",
    "BoxGeometryExtractor",
    "Classification",
    "ComponentConfig",
    "FrozenBoxDetector",
    "GeometryError",
    "GalleryQueryPrior",
    "GroundingDINOBoxDetector",
    "InstanceSelector",
    "ObjectInstance",
    "ObservedGeometry",
    "PerceptionConfig",
    "PerceptionDiagnostics",
    "PointCloud",
    "PublicAssetGallerySpec",
    "RGBDFrame",
    "RouteBScenePerceptionAdapter",
    "RouteCSceneEstimatorAdapter",
    "SceneObservation",
    "SelectorKind",
    "SensorOnlyScenePerception",
    "TextureSizeGallery",
    "backproject_frame",
    "center_ray_intersection",
    "coerce_rgbd_frame",
    "collision_aabb_dimensions",
    "connected_components_3d",
    "estimate_horizontal_support",
    "fit_observed_geometry",
    "fuse_instances_3d",
    "fuse_rgbd_frames",
    "hsv_histogram",
    "make_default_perception",
    "normalize_label",
    "resolve_geometric_selector",
    "scene_camera_capture_ids",
    "scene_capture_id",
]
